server:
  port: 8010

spring:
  datasource:
    username: root
    password: lyun@mysqlzxx
    url: jdbc:mysql://120.26.210.135:13306/cpdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true

