server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://120.26.210.135:13306/cpdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
    username: root
    password: lyun@mysqlzxx
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 15
      # Redis服务器地址
      host: 120.26.210.135
      # Redis服务器连接端口
      port: 16379
      # Redis服务器连接密码（默认为空）
      password: lyun@rediszxx
      # 连接超时时间
      timeout: 2s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  mail:
    host: smtp.163.com
    username: 13960486856@163.com
    # 241027-180
    password: XJrM5fySAM5rSTVk
    port: 465
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

auth:
  salt: abcdtest

